from pathlib import Path


SOURCE = Path(r"C:\Users\MIKE\Documents\Codex\YT\deliverables\sentence_visual_prompts_numbered.md")
TARGET = Path(r"C:\Users\MIKE\Documents\Codex\YT\deliverables\sentence_visual_prompts_numbered_with_refs.md")


REF_MAP = {
    1: "Ref: Journalist",
    2: "No Ref",
    3: "Ref: Journalist",
    4: "Ref: Journalist",
    5: "Ref: Journalist",
    6: "Ref: Journalist",
    7: "Ref: Journalist",
    8: "Ref: Journalist",
    9: "Ref: Journalist",
    10: "Ref: Journalist",
    11: "Ref: Journalist",
    12: "No Ref",
    13: "No Ref",
    14: "Ref: Journalist",
    15: "No Ref",
    16: "No Ref",
    17: "No Ref",
    18: "No Ref",
    19: "Ref: Crime Boss",
    20: "Ref: Crime Boss",
    21: "Ref: Crime Boss",
    22: "Ref: Crime Boss",
    23: "Ref: Crime Boss",
    24: "Ref: Crime Boss",
    25: "Ref: Crime Boss",
    26: "Ref: Crime Boss",
    27: "Ref: Journalist, Crime Boss",
    28: "Ref: Crime Boss",
    29: "No Ref",
    30: "Ref: Journalist, Crime Boss",
    31: "No Ref",
    32: "No Ref",
    33: "No Ref",
    34: "No Ref",
    35: "No Ref",
    36: "No Ref",
    37: "No Ref",
    38: "No Ref",
    39: "No Ref",
    40: "No Ref",
    41: "No Ref",
    42: "No Ref",
    43: "No Ref",
    44: "No Ref",
    45: "No Ref",
    46: "No Ref",
    47: "No Ref",
    48: "No Ref",
    49: "No Ref",
    50: "No Ref",
    51: "No Ref",
    52: "No Ref",
    53: "Ref: Founder Engineer",
    54: "Ref: Founder Engineer",
    55: "No Ref",
    56: "No Ref",
    57: "No Ref",
    58: "No Ref",
    59: "No Ref",
    60: "Ref: Journalist, Crime Boss",
    61: "No Ref",
    62: "No Ref",
    63: "No Ref",
    64: "No Ref",
    65: "No Ref",
    66: "No Ref",
    67: "No Ref",
    68: "No Ref",
    69: "No Ref",
    70: "No Ref",
    71: "No Ref",
    72: "No Ref",
    73: "No Ref",
    74: "No Ref",
    75: "No Ref",
    76: "No Ref",
    77: "No Ref",
    78: "No Ref",
    79: "No Ref",
    80: "No Ref",
    81: "No Ref",
    82: "Ref: Crime Boss",
    83: "No Ref",
    84: "No Ref",
    85: "Ref: Teenage Recruit",
    86: "Ref: Teenage Recruit",
    87: "Ref: Teenage Recruit",
    88: "No Ref",
    89: "No Ref",
    90: "No Ref",
    91: "No Ref",
    92: "No Ref",
    93: "No Ref",
    94: "No Ref",
    95: "No Ref",
    96: "No Ref",
    97: "Ref: Cryptophone Entrepreneur",
    98: "No Ref",
    99: "No Ref",
    100: "No Ref",
    101: "No Ref",
    102: "No Ref",
    103: "No Ref",
    104: "Ref: Cryptophone Entrepreneur",
    105: "No Ref",
    106: "No Ref",
    107: "Ref: Intelligence Analyst",
    108: "No Ref",
    109: "No Ref",
    110: "No Ref",
    111: "No Ref",
    112: "No Ref",
    113: "No Ref",
    114: "No Ref",
    115: "No Ref",
    116: "Ref: Intelligence Analyst",
    117: "No Ref",
    118: "No Ref",
    119: "No Ref",
    120: "No Ref",
    121: "No Ref",
    122: "No Ref",
    123: "No Ref",
    124: "No Ref",
    125: "No Ref",
    126: "No Ref",
    127: "No Ref",
    128: "No Ref",
    129: "No Ref",
    130: "No Ref",
    131: "No Ref",
    132: "No Ref",
    133: "Ref: Teenage Recruit",
    134: "Ref: Teenage Recruit",
    135: "Ref: Teenage Recruit",
    136: "Ref: Teenage Recruit",
    137: "Ref: Teenage Recruit",
    138: "Ref: Teenage Recruit",
    139: "Ref: Teenage Recruit",
    140: "No Ref",
    141: "No Ref",
    142: "No Ref",
    143: "No Ref",
    144: "No Ref",
    145: "No Ref",
    146: "No Ref",
    147: "No Ref",
    148: "No Ref",
    149: "No Ref",
    150: "No Ref",
    151: "No Ref",
    152: "No Ref",
    153: "No Ref",
    154: "No Ref",
    155: "No Ref",
    156: "No Ref",
    157: "No Ref",
    158: "No Ref",
    159: "No Ref",
    160: "No Ref",
    161: "No Ref",
    162: "No Ref",
    163: "No Ref",
    164: "No Ref",
    165: "No Ref",
    166: "No Ref",
    167: "No Ref",
    168: "No Ref",
    169: "No Ref",
    170: "No Ref",
    171: "No Ref",
    172: "No Ref",
    173: "No Ref",
    174: "Ref: Crime Boss",
    175: "No Ref",
    176: "No Ref",
    177: "No Ref",
    178: "No Ref",
    179: "No Ref",
    180: "No Ref",
    181: "No Ref",
    182: "No Ref",
    183: "No Ref",
    184: "No Ref",
    185: "No Ref",
    186: "No Ref",
    187: "No Ref",
    188: "No Ref",
}


def main() -> None:
    blocks = [block.strip() for block in SOURCE.read_text(encoding="utf-8").split("\n\n") if block.strip()]
    lines = []
    for block in blocks:
        block_lines = block.splitlines()
        number_line = block_lines[0].strip()
        prompt_line = "\n".join(block_lines[1:]).strip()
        index = int(number_line[:-1])
        ref_line = REF_MAP[index]
        lines.append(number_line)
        lines.append(ref_line)
        lines.append(prompt_line)
        lines.append("")
    TARGET.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(TARGET)


if __name__ == "__main__":
    main()
